extends Node2D

class_name FmodFlags

const FmodInitFlags = {
	FMOD_INIT_NORMAL = "FMOD_INIT_NORMAL",
	FMOD_INIT_STREAM_FROM_UPDATE = "FMOD_INIT_STREAM_FROM_UPDATE",
	FMOD_INIT_MIX_FROM_UPDATE = "FMOD_INIT_MIX_FROM_UPDATE",
	FMOD_INIT_3D_RIGHTHANDED = "FMOD_INIT_3D_RIGHTHANDED",
	FMOD_INIT_CHANNEL_LOWPASS = "FMOD_INIT_CHANNEL_LOWPASS",
	FMOD_INIT_CHANNEL_DISTANCEFILTER = "FMOD_INIT_CHANNEL_DISTANCEFILTER",
	FMOD_INIT_PROFILE_ENABLE = "FMOD_INIT_PROFILE_ENABLE",
	FMOD_INIT_VOL0_BECOMES_VIRTUAL = "FMOD_INIT_VOL0_BECOMES_VIRTUAL",
	FMOD_INIT_GEOMETRY_USECLOSEST = "FMOD_INIT_GEOMETRY_USECLOSEST",
	FMOD_INIT_PREFER_DOLBY_DOWNMIX = "FMOD_INIT_PREFER_DOLBY_DOWNMIX",
	FMOD_INIT_THREAD_UNSAFE = "FMOD_INIT_THREAD_UNSAFE",
	FMOD_INIT_PROFILE_METER_ALL = "FMOD_INIT_PROFILE_METER_ALL",
	FMOD_INIT_DISABLE_SRS_HIGHPASSFILTER = "FMOD_INIT_DISABLE_SRS_HIGHPASSFILTER"
}

const FmodStudioInitFlags = {
	FMOD_STUDIO_INIT_NORMAL = "FMOD_STUDIO_INIT_NORMAL",
	FMOD_STUDIO_INIT_LIVEUPDATE = "FMOD_STUDIO_INIT_LIVEUPDATE",
	FMOD_STUDIO_INIT_ALLOW_MISSING_PLUGINS = "FMOD_STUDIO_INIT_ALLOW_MISSING_PLUGINS",
	FMOD_STUDIO_INIT_SYNCHRONOUS_UPDATE = "FMOD_STUDIO_INIT_SYNCHRONOUS_UPDATE",
	FMOD_STUDIO_INIT_DEFERRED_CALLBACKS = "FMOD_STUDIO_INIT_DEFERRED_CALLBACKS",
	FMOD_STUDIO_INIT_LOAD_FROM_UPDATE = "FMOD_STUDIO_INIT_LOAD_FROM_UPDATE"
}

const FmodSpeakerModeFlags = {
	FMOD_SPEAKERMODE_DEFAULT = "FMOD_SPEAKERMODE_DEFAULT",
	FMOD_SPEAKERMODE_RAW = "FMOD_SPEAKERMODE_RAW",
	FMOD_SPEAKERMODE_MONO = "FMOD_SPEAKERMODE_MONO",
	FMOD_SPEAKERMODE_STEREO = "FMOD_SPEAKERMODE_STEREO",
	FMOD_SPEAKERMODE_QUAD = "FMOD_SPEAKERMODE_QUAD",
	FMOD_SPEAKERMODE_SURROUND = "FMOD_SPEAKERMODE_SURROUND",
	FMOD_SPEAKERMODE_5POINT1 = "FMOD_SPEAKERMODE_5POINT1",
	FMOD_SPEAKERMODE_7POINT1 = "FMOD_SPEAKERMODE_7POINT1",
	FMOD_SPEAKERMODE_7POINT1POINT4 = "FMOD_SPEAKERMODE_7POINT1POINT4",
	FMOD_SPEAKERMODE_MAX = "FMOD_SPEAKERMODE_MAX"
}

const FmodLoadBankFlags = {
	FMOD_STUDIO_LOAD_BANK_NORMAL = "FMOD_STUDIO_LOAD_BANK_NORMAL",
	FMOD_STUDIO_LOAD_BANK_NONBLOCKING = "FMOD_STUDIO_LOAD_BANK_NONBLOCKING",
	FMOD_STUDIO_LOAD_BANK_DECOMPRESS_SAMPLES = "FMOD_STUDIO_LOAD_BANK_DECOMPRESS_SAMPLES"
}

const fmodSoundConstants = {
	FMOD_DEFAULT = "FMOD_DEFAULT",
	FMOD_LOOP_OFF = "FMOD_LOOP_OFF",
	FMOD_LOOP_NORMAL = "FMOD_LOOP_NORMAL",
	FMOD_LOOP_BIDI = "FMOD_LOOP_BIDI",
	FMOD_2D = "FMOD_2D",
	FMOD_3D = "FMOD_3D",
	FMOD_CREATESTREAM = "FMOD_CREATESTREAM",
	FMOD_CREATESAMPLE = "FMOD_CREATESAMPLE",
	FMOD_CREATECOMPRESSEDSAMPLE = "FMOD_CREATECOMPRESSEDSAMPLE",
	FMOD_OPENUSER = "FMOD_OPENUSER",
	FMOD_OPENMEMORY = "FMOD_OPENMEMORY",
	FMOD_OPENMEMORY_POINT = "FMOD_OPENMEMORY_POINT",
	FMOD_OPENRAW = "FMOD_OPENRAW",
	FMOD_OPENONLY = "FMOD_OPENONLY",
	FMOD_ACCURATETIME = "FMOD_ACCURATETIME",
	FMOD_MPEGSEARCH = "FMOD_MPEGSEARCH",
	FMOD_NONBLOCKING = "FMOD_NONBLOCKING",
	FMOD_UNIQUE = "FMOD_UNIQUE",
	FMOD_3D_HEADRELATIVE = "FMOD_3D_HEADRELATIVE",
	FMOD_3D_WORLDRELATIVE = "FMOD_3D_WORLDRELATIVE",
	FMOD_3D_INVERSEROLLOFF = "FMOD_3D_INVERSEROLLOFF",
	FMOD_3D_LINEARROLLOFF = "FMOD_3D_LINEARROLLOFF",
	FMOD_3D_LINEARSQUAREROLLOFF = "FMOD_3D_LINEARSQUAREROLLOFF",
	FMOD_3D_INVERSETAPEREDROLLOFF = "FMOD_3D_INVERSETAPEREDROLLOFF",
	FMOD_3D_CUSTOMROLLOFF = "FMOD_3D_CUSTOMROLLOFF",
	FMOD_3D_IGNOREGEOMETRY = "FMOD_3D_IGNOREGEOMETRY",
	FMOD_IGNORETAGS = "FMOD_IGNORETAGS",
	FMOD_LOWMEM = "FMOD_LOWMEM",
	FMOD_VIRTUAL_PLAYFROMSTART = "FMOD_VIRTUAL_PLAYFROMSTART"
}

const fmodStudioStopModes = {
	FMOD_STUDIO_STOP_ALLOWFADEOUT = "FMOD_STUDIO_STOP_ALLOWFADEOUT",
	FMOD_STUDIO_STOP_IMMEDIATE = "FMOD_STUDIO_STOP_IMMEDIATE",
	FMOD_STUDIO_STOP_FORCEINT = "FMOD_STUDIO_STOP_FORCEINT"
}